/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Dashboard;

import Master.*;
import Transaksi.*;
import Koneksi.Koneksi;
import java.awt.Color;
import java.awt.GraphicsEnvironment;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author Lenovo
 */
public class DashboardAdmin extends javax.swing.JFrame {

    boolean[] stat = new boolean[6];
    boolean[] tunjuk = new boolean[6];

    Barang var_barang;
    Distributor var_distributor;
    User var_user;
    Pemasokan var_pemasokan;
    Transaksi var_transaksi;
    Laporan var_laporan;

    boolean maximized = true;

    /**
     * Creates new form DashboardAdmin
     */
    public DashboardAdmin() {
        initComponents();
        fullscreen();
        resetstat();
        awalProgram();
    }

    private void fullscreen() {
        if (maximized) {
            DashboardAdmin.this.setExtendedState(JFrame.MAXIMIZED_BOTH);
            GraphicsEnvironment env = GraphicsEnvironment.getLocalGraphicsEnvironment();
            DashboardAdmin.this.setMaximizedBounds(env.getMaximumWindowBounds());
            maximized = false;
        } else {
            setExtendedState(JFrame.NORMAL);
            maximized = true;
        }
    }

    private void resetstat() {
        for (int i = 0; i < 6; i++) {
            stat[i] = false;
        }
    }

    private void hide_pane() {
        if (stat[0] == true) {
            var_user.dispose();
        }
        if (stat[1] == true) {
            var_distributor.dispose();
        }
        if (stat[2] == true) {
            var_barang.dispose();
        }
        if (stat[3] == true) {
            var_transaksi.dispose();
        }
        if (stat[4] == true) {
            var_pemasokan.dispose();
        }
        if (stat[5] == true) {
            var_laporan.dispose();
        }
        resetstat();
    }

    private void resetTunjuk() {
        for (int i = 0; i < 6; i++) {
            tunjuk[i] = false;
        }
    }

    private void setWarna(JPanel panel) {
        panel.setBackground(new Color(112, 112, 112));
    }

    private void resetWarna(JPanel[] panel) {
        for (int i = 0; i < panel.length; i++) {
            panel[i].setBackground(new Color(65, 65, 65));
        }
    }

    private void setHover(JPanel panel) {
        panel.setBackground(new Color(89, 89, 89));
    }

    private void resetHover(JPanel panel) {
        panel.setBackground(new Color(65, 65, 65));
    }
    
    private void awalProgram() {
        resetTunjuk();
        tunjuk[0] = true;
        resetWarna(new JPanel[]{btn_user, btn_distributor, btn_barang, btn_transaksi, btn_pemasokan, btn_laporan});
        setWarna(btn_user);

        // memanggil jInternalFrame        
        hide_pane();
        stat[0] = true;
        var_user = new User();
        dekstop_pane.add(var_user);
        var_user.setVisible(true);

        //addToPane();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_utama = new javax.swing.JPanel();
        sub_menu_barang = new javax.swing.JPanel();
        panel_menu = new javax.swing.JPanel();
        judul_aplikasi = new javax.swing.JLabel();
        btn_user = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_distributor = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btn_barang = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btn_transaksi = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btn_pemasokan = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btn_laporan = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        panel_body = new javax.swing.JPanel();
        dekstop_pane = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_utama.setPreferredSize(new java.awt.Dimension(1366, 768));
        panel_utama.setLayout(null);

        sub_menu_barang.setBackground(new java.awt.Color(112, 112, 112));

        javax.swing.GroupLayout sub_menu_barangLayout = new javax.swing.GroupLayout(sub_menu_barang);
        sub_menu_barang.setLayout(sub_menu_barangLayout);
        sub_menu_barangLayout.setHorizontalGroup(
            sub_menu_barangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );
        sub_menu_barangLayout.setVerticalGroup(
            sub_menu_barangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        panel_utama.add(sub_menu_barang);
        sub_menu_barang.setBounds(820, 70, 140, 150);

        panel_menu.setBackground(new java.awt.Color(65, 65, 65));
        panel_menu.setPreferredSize(new java.awt.Dimension(1366, 100));
        panel_menu.setLayout(null);

        judul_aplikasi.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 36)); // NOI18N
        judul_aplikasi.setForeground(new java.awt.Color(102, 102, 255));
        judul_aplikasi.setText("SUMBER REJEKI");
        panel_menu.add(judul_aplikasi);
        judul_aplikasi.setBounds(20, 20, 390, 60);

        btn_user.setBackground(new java.awt.Color(112, 112, 112));
        btn_user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_userMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_userMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_userMouseExited(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Swis721 Hv BT", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("USER");

        javax.swing.GroupLayout btn_userLayout = new javax.swing.GroupLayout(btn_user);
        btn_user.setLayout(btn_userLayout);
        btn_userLayout.setHorizontalGroup(
            btn_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_userLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1)
                .addContainerGap(46, Short.MAX_VALUE))
        );
        btn_userLayout.setVerticalGroup(
            btn_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_userLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel_menu.add(btn_user);
        btn_user.setBounds(560, 30, 130, 40);

        btn_distributor.setBackground(new java.awt.Color(112, 112, 112));
        btn_distributor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_distributorMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_distributorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_distributorMouseExited(evt);
            }
        });
        btn_distributor.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Swis721 Hv BT", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("DISTRIBUTOR");
        btn_distributor.add(jLabel2);
        jLabel2.setBounds(20, 10, 99, 18);

        panel_menu.add(btn_distributor);
        btn_distributor.setBounds(690, 30, 130, 40);

        btn_barang.setBackground(new java.awt.Color(112, 112, 112));
        btn_barang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_barangMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_barangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_barangMouseExited(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Swis721 Hv BT", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("BARANG");

        javax.swing.GroupLayout btn_barangLayout = new javax.swing.GroupLayout(btn_barang);
        btn_barang.setLayout(btn_barangLayout);
        btn_barangLayout.setHorizontalGroup(
            btn_barangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_barangLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel3)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        btn_barangLayout.setVerticalGroup(
            btn_barangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_barangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel_menu.add(btn_barang);
        btn_barang.setBounds(820, 30, 130, 40);

        btn_transaksi.setBackground(new java.awt.Color(112, 112, 112));
        btn_transaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_transaksiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_transaksiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_transaksiMouseExited(evt);
            }
        });
        btn_transaksi.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Swis721 Hv BT", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("TRANSAKSI");
        btn_transaksi.add(jLabel4);
        jLabel4.setBounds(20, 10, 90, 18);

        panel_menu.add(btn_transaksi);
        btn_transaksi.setBounds(950, 30, 130, 40);

        btn_pemasokan.setBackground(new java.awt.Color(112, 112, 112));
        btn_pemasokan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_pemasokanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_pemasokanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_pemasokanMouseExited(evt);
            }
        });
        btn_pemasokan.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Swis721 Hv BT", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("PEMASOKAN");
        btn_pemasokan.add(jLabel5);
        jLabel5.setBounds(20, 10, 94, 18);

        panel_menu.add(btn_pemasokan);
        btn_pemasokan.setBounds(1080, 30, 130, 40);

        btn_laporan.setBackground(new java.awt.Color(112, 112, 112));
        btn_laporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_laporanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_laporanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_laporanMouseExited(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Swis721 Hv BT", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("LAPORAN");

        javax.swing.GroupLayout btn_laporanLayout = new javax.swing.GroupLayout(btn_laporan);
        btn_laporan.setLayout(btn_laporanLayout);
        btn_laporanLayout.setHorizontalGroup(
            btn_laporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_laporanLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel6)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        btn_laporanLayout.setVerticalGroup(
            btn_laporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_laporanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel_menu.add(btn_laporan);
        btn_laporan.setBounds(1210, 30, 130, 40);

        panel_utama.add(panel_menu);
        panel_menu.setBounds(0, 0, 1366, 100);

        panel_body.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout dekstop_paneLayout = new javax.swing.GroupLayout(dekstop_pane);
        dekstop_pane.setLayout(dekstop_paneLayout);
        dekstop_paneLayout.setHorizontalGroup(
            dekstop_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1366, Short.MAX_VALUE)
        );
        dekstop_paneLayout.setVerticalGroup(
            dekstop_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );

        panel_body.add(dekstop_pane, "card2");

        panel_utama.add(panel_body);
        panel_body.setBounds(0, 100, 1366, 670);

        getContentPane().add(panel_utama, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_userMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_userMouseClicked
        // TODO add your handling code here:
        // warna menu  
        resetTunjuk();
        tunjuk[0] = true;
        resetWarna(new JPanel[]{btn_user, btn_distributor, btn_barang, btn_transaksi, btn_pemasokan, btn_laporan});
        setWarna(btn_user);

        // memanggil jInternalFrame        
        hide_pane();
        stat[0] = true;
        var_user = new User();
        dekstop_pane.add(var_user);
        var_user.setVisible(true);
    }//GEN-LAST:event_btn_userMouseClicked

    private void btn_distributorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_distributorMouseClicked
        // TODO add your handling code here:
        // warna menu
        resetTunjuk();
        tunjuk[1] = true;
        resetWarna(new JPanel[]{btn_user, btn_distributor, btn_barang, btn_transaksi, btn_pemasokan, btn_laporan});
        setWarna(btn_distributor);

        // memanggil jInternalFrame     
        hide_pane();
        stat[1] = true;
        var_distributor = new Distributor();
        dekstop_pane.add(var_distributor);
        var_distributor.setVisible(true);
    }//GEN-LAST:event_btn_distributorMouseClicked

    private void btn_barangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_barangMouseClicked
        // TODO add your handling code here:
        // warna menu
        resetTunjuk();
        tunjuk[2] = true;
        resetWarna(new JPanel[]{btn_user, btn_distributor, btn_barang, btn_transaksi, btn_pemasokan, btn_laporan});
        setWarna(btn_barang);

        // memanggil jInternalFrame 
        hide_pane();
        stat[2] = true;
        var_barang = new Barang();
        dekstop_pane.add(var_barang);
        var_barang.setVisible(true);
    }//GEN-LAST:event_btn_barangMouseClicked

    private void btn_transaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_transaksiMouseClicked
        // TODO add your handling code here:
        // warna menu
        resetTunjuk();
        tunjuk[3] = true;
        resetWarna(new JPanel[]{btn_user, btn_distributor, btn_barang, btn_transaksi, btn_pemasokan, btn_laporan});
        setWarna(btn_transaksi);

        // memanggil jInternalFrame 
        hide_pane();
        stat[3] = true;
        var_transaksi = new Transaksi();
        dekstop_pane.add(var_transaksi);
        var_transaksi.setVisible(true);
    }//GEN-LAST:event_btn_transaksiMouseClicked

    private void btn_pemasokanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pemasokanMouseClicked
        // TODO add your handling code here:
        // warna menu
        resetTunjuk();
        tunjuk[4] = true;
        resetWarna(new JPanel[]{btn_user, btn_distributor, btn_barang, btn_transaksi, btn_pemasokan, btn_laporan});
        setWarna(btn_pemasokan);

        // memanggil jInternalFrame 
        hide_pane();
        stat[4] = true;
        var_pemasokan = new Pemasokan();
        dekstop_pane.add(var_pemasokan);
        var_pemasokan.setVisible(true);
    }//GEN-LAST:event_btn_pemasokanMouseClicked

    private void btn_laporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_laporanMouseClicked
        // TODO add your handling code here:
        // warna menu
        resetTunjuk();
        tunjuk[5] = true;
        resetWarna(new JPanel[]{btn_user, btn_distributor, btn_barang, btn_transaksi, btn_pemasokan, btn_laporan});
        setWarna(btn_laporan);

        // memanggil jInternalFrame 
        hide_pane();
        stat[5] = true;
        var_laporan = new Laporan();
        dekstop_pane.add(var_laporan);
        var_laporan.setVisible(true);
    }//GEN-LAST:event_btn_laporanMouseClicked

    private void btn_userMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_userMouseEntered
        // TODO add your handling code here:
        if (tunjuk[0] == false) {
            setHover(btn_user);
        }
    }//GEN-LAST:event_btn_userMouseEntered

    private void btn_userMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_userMouseExited
        // TODO add your handling code here:
        if (tunjuk[0] == false) {
            resetHover(btn_user);
        }
    }//GEN-LAST:event_btn_userMouseExited

    private void btn_distributorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_distributorMouseEntered
        // TODO add your handling code here:
        if (tunjuk[1] == false) {
            setHover(btn_distributor);
        }
    }//GEN-LAST:event_btn_distributorMouseEntered

    private void btn_distributorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_distributorMouseExited
        // TODO add your handling code here:
        if (tunjuk[1] == false) {
            resetHover(btn_distributor);
        }
    }//GEN-LAST:event_btn_distributorMouseExited

    private void btn_barangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_barangMouseEntered
        // TODO add your handling code here:
        if (tunjuk[2] == false) {
            setHover(btn_barang);
        }
    }//GEN-LAST:event_btn_barangMouseEntered

    private void btn_barangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_barangMouseExited
        // TODO add your handling code here:
        if (tunjuk[2] == false) {
            resetHover(btn_barang);
        }
    }//GEN-LAST:event_btn_barangMouseExited

    private void btn_transaksiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_transaksiMouseEntered
        // TODO add your handling code here:
        if (tunjuk[3] == false) {
            setHover(btn_transaksi);
        }
    }//GEN-LAST:event_btn_transaksiMouseEntered

    private void btn_transaksiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_transaksiMouseExited
        // TODO add your handling code here:
        if (tunjuk[3] == false) {
            resetHover(btn_transaksi);
        }
    }//GEN-LAST:event_btn_transaksiMouseExited

    private void btn_pemasokanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pemasokanMouseEntered
        // TODO add your handling code here:
        if (tunjuk[4] == false) {
            setHover(btn_pemasokan);
        }
    }//GEN-LAST:event_btn_pemasokanMouseEntered

    private void btn_pemasokanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pemasokanMouseExited
        // TODO add your handling code here:
        if (tunjuk[4] == false) {
            resetHover(btn_pemasokan);
        }
    }//GEN-LAST:event_btn_pemasokanMouseExited

    private void btn_laporanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_laporanMouseEntered
        // TODO add your handling code here:
        if (tunjuk[5] == false) {
            setHover(btn_laporan);
        }
    }//GEN-LAST:event_btn_laporanMouseEntered

    private void btn_laporanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_laporanMouseExited
        // TODO add your handling code here:
        if (tunjuk[5] == false) {
            resetHover(btn_laporan);
        }
    }//GEN-LAST:event_btn_laporanMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btn_barang;
    private javax.swing.JPanel btn_distributor;
    private javax.swing.JPanel btn_laporan;
    private javax.swing.JPanel btn_pemasokan;
    private javax.swing.JPanel btn_transaksi;
    private javax.swing.JPanel btn_user;
    private javax.swing.JDesktopPane dekstop_pane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel judul_aplikasi;
    private javax.swing.JPanel panel_body;
    private javax.swing.JPanel panel_menu;
    private javax.swing.JPanel panel_utama;
    private javax.swing.JPanel sub_menu_barang;
    // End of variables declaration//GEN-END:variables
}
