/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Dashboard;
import Master.*;
import Koneksi.Koneksi;
import java.awt.GraphicsEnvironment;
import javax.swing.JFrame;
/**
 *
 * @author Lenovo
 */
public class DashboardAdmin extends javax.swing.JFrame {
    boolean[] stat = new boolean[3];
    User var_user;
    Akses var_akses;
    
    boolean maximized = true;
    /**
     * Creates new form DashboardAdmin
     */
    public DashboardAdmin() {
        initComponents();
        fullscreen();
        resetstat();
    }
    
    private void fullscreen() {
        if (maximized) {
            DashboardAdmin.this.setExtendedState(JFrame.MAXIMIZED_BOTH);
            GraphicsEnvironment env = GraphicsEnvironment.getLocalGraphicsEnvironment();
            DashboardAdmin.this.setMaximizedBounds(env.getMaximumWindowBounds());
            maximized = false;
        } else {
            setExtendedState(JFrame.NORMAL);
            maximized = true;
        }
    }
    
    private void addToPane() {
        dekstop_pane.add(var_akses);
        dekstop_pane.add(var_user);

    }
    private void resetstat() {
        for (int i = 0; i < 1; i++) {
            stat[i] = false;
        }
    }
    private void hide_pane() {
        if (stat[0] == true) {
            var_akses.dispose();
        }
        if (stat[1] == true) {
            var_user.dispose();
        }
        resetstat();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_menu = new javax.swing.JPanel();
        menu_user = new javax.swing.JButton();
        menu_distributor = new javax.swing.JButton();
        menu_barang = new javax.swing.JButton();
        menu_transaksi = new javax.swing.JButton();
        menu_transaksi1 = new javax.swing.JButton();
        judul_aplikasi = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        dekstop_pane = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_menu.setPreferredSize(new java.awt.Dimension(1366, 100));
        panel_menu.setLayout(null);

        menu_user.setText("USER");
        menu_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_userActionPerformed(evt);
            }
        });
        panel_menu.add(menu_user);
        menu_user.setBounds(616, 30, 120, 45);

        menu_distributor.setText("DISTRIBUTOR");
        panel_menu.add(menu_distributor);
        menu_distributor.setBounds(766, 30, 120, 45);

        menu_barang.setText("BARANG");
        panel_menu.add(menu_barang);
        menu_barang.setBounds(916, 30, 120, 45);

        menu_transaksi.setText("TRANSAKSI");
        panel_menu.add(menu_transaksi);
        menu_transaksi.setBounds(1066, 30, 120, 45);

        menu_transaksi1.setText("PEMASOKAN");
        panel_menu.add(menu_transaksi1);
        menu_transaksi1.setBounds(1216, 30, 120, 45);

        judul_aplikasi.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 36)); // NOI18N
        judul_aplikasi.setForeground(new java.awt.Color(102, 102, 255));
        judul_aplikasi.setText("SUMBER REJEKI");
        panel_menu.add(judul_aplikasi);
        judul_aplikasi.setBounds(20, 20, 390, 60);

        getContentPane().add(panel_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1366, -1));

        jPanel1.setLayout(null);

        javax.swing.GroupLayout dekstop_paneLayout = new javax.swing.GroupLayout(dekstop_pane);
        dekstop_pane.setLayout(dekstop_paneLayout);
        dekstop_paneLayout.setHorizontalGroup(
            dekstop_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        dekstop_paneLayout.setVerticalGroup(
            dekstop_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );

        jPanel1.add(dekstop_pane);
        dekstop_pane.setBounds(0, 0, 1366, 670);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1366, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menu_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_userActionPerformed
        // TODO add your handling code here:
        hide_pane();
        stat[1] = true;
        var_user  = new User();
        dekstop_pane.add(var_user);
        var_user.setVisible(true);
    }//GEN-LAST:event_menu_userActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dekstop_pane;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel judul_aplikasi;
    private javax.swing.JButton menu_barang;
    private javax.swing.JButton menu_distributor;
    private javax.swing.JButton menu_transaksi;
    private javax.swing.JButton menu_transaksi1;
    private javax.swing.JButton menu_user;
    private javax.swing.JPanel panel_menu;
    // End of variables declaration//GEN-END:variables
}
