/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Master;

import java.awt.Font;
import java.awt.FontMetrics;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Paper;
import java.awt.print.Printable;
import static java.awt.print.Printable.NO_SUCH_PAGE;
import static java.awt.print.Printable.PAGE_EXISTS;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;

/**
 *
 * @author zakka
 */
public class DataStok extends javax.swing.JInternalFrame {

    /**
     * Creates new form DataStok
     */
    public DataStok() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        brg = new javax.swing.JTextField();
        hrg = new javax.swing.JTextField();
        print = new javax.swing.JButton();
        jml = new javax.swing.JTextField();

        jLabel1.setText("Nama");

        print.setText("PRINT");
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(print)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(brg, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jml, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(hrg, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(954, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(brg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jml, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(print)
                .addContainerGap(469, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public PageFormat getPageFormat(PrinterJob pj)
    {

        PageFormat pf = pj.defaultPage();
        Paper paper = pf.getPaper();    

        double middleHeight =8.0;  
        double headerHeight = 2.0;                  
        double footerHeight = 2.0;                  
        double width = convert_CM_To_PPI(8);      //printer know only point per inch.default value is 72ppi
        double height = convert_CM_To_PPI(headerHeight+middleHeight+footerHeight); 
        paper.setSize(width, height);
        paper.setImageableArea(                    
            0,
            10,
            width,            
            height - convert_CM_To_PPI(1)
        );   //define boarder size    after that print area width is about 180 points

        pf.setOrientation(PageFormat.PORTRAIT);           //select orientation portrait or landscape but for this time portrait
        pf.setPaper(paper);    

        return pf;
    }
    
    protected static double convert_CM_To_PPI(double cm) 
    {            
	return toPPI(cm * 0.393600787);            
    }
 
    protected static double toPPI(double inch) 
    {            
        return inch * 72d;            
    }
    
    public class BillPrintable implements Printable 
    {
    
  
        public int print(Graphics graphics, PageFormat pageFormat,int pageIndex) 
        throws PrinterException 
        {    
      
                
        
            int result = NO_SUCH_PAGE;    
              if (pageIndex == 0) 
                {                    

                  Graphics2D g2d = (Graphics2D) graphics;
                  double width = pageFormat.getImageableWidth();                    
                  g2d.translate((int) pageFormat.getImageableX(),(int) pageFormat.getImageableY()); 

                  
              try{
                  /*Draw Header*/
                  int y=20;
                  int yShift = 10;
                  int headerRectHeight=15;
                  int headerRectHeighta=40;

                  ///////////////// Product names Get ///////////
                      String  brgs=brg.getText();
                  ///////////////// Product names Get ///////////


                  ///////////////// Product price Get ///////////
                  int jmls =Integer.valueOf(jml.getText());
                  ///////////////// Product price Get ///////////

                  String a = hrg.getText();
                  String x = String.format("%1$10s", a);
                  String b = "2000000";
                  String z = String.format("%1$10s", b);
                  g2d.setFont(new Font("Monospaced",Font.PLAIN,7));

                  g2d.drawString("            SUMBER REJEKI            ",12,y);y+=yShift;
                  g2d.drawString("       Jl. Raya Tongas No.189        ",12,y);y+=yShift;
                  g2d.drawString("          Telp 082234568912          ",12,y);y+=yShift;
                  g2d.drawString("                                     ",10,y);y+=yShift;
                  g2d.drawString("ID  : T0000000001    Kasir : Sapri   ",10,y);y+=yShift;
                  g2d.drawString("Tgl : 23/01/2019 22:20:12         ",10,y);y+=yShift;
                  g2d.drawString("-------------------------------------",10,y);y+=yShift;
                  g2d.drawString("                                     ",10,y);y+=yShift;
                  g2d.drawString(" "+brgs+"                            ",10,y);y+=yShift;
                  g2d.drawString("                           "+x+"",10,y);y+=yShift;
                  g2d.drawString(" "+brgs+"                            ",10,y);y+=yShift;
                  g2d.drawString("      "+jmls+"   x   "+a+"      "+z+"",10,y);y+=yShift;
                  g2d.drawString(" "+brgs+"                            ",10,y);y+=yShift;
                  g2d.drawString("      "+jmls+"   x   "+a+"      "+x+"",10,y);y+=yShift;
                  g2d.drawString(" "+brgs+"                            ",10,y);y+=yShift;
                  g2d.drawString("      "+jmls+"   x   "+a+"      "+x+"",10,y);y+=yShift;
                  g2d.drawString("-------------------------------------",10,y);y+=yShift;
                  g2d.drawString("                           "+x+"",10,y);y+=yShift;
                  g2d.drawString("-------------------------------------",10,y);y+=yShift;
                  g2d.drawString("          Free Home Delivery         ",10,y);y+=yShift;
                  g2d.drawString("             03111111111             ",10,y);y+=yShift;
                  g2d.drawString("*************************************",10,y);y+=yShift;
                  g2d.drawString("    THANKS TO VISIT OUR RESTUARANT   ",10,y);y+=yShift;
                  g2d.drawString("*************************************",10,y);y+=yShift;





      //            g2d.setFont(new Font("Monospaced",Font.BOLD,10));
      //            g2d.drawString("Customer Shopping Invoice", 30,y);y+=yShift; 


                   }
                   catch(Exception r){
                   r.printStackTrace();
                   }

                   result = PAGE_EXISTS;    
                }    
                    return result;    
        }
   }
    
    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
        // TODO add your handling code here:
        PrinterJob pj = PrinterJob.getPrinterJob();        
        pj.setPrintable(new BillPrintable(),getPageFormat(pj));
        try {
             pj.print();
          
        }
         catch (PrinterException ex) {
                 ex.printStackTrace();
        }
    }//GEN-LAST:event_printActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField brg;
    private javax.swing.JTextField hrg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jml;
    private javax.swing.JButton print;
    // End of variables declaration//GEN-END:variables
}
